/*
 * Copyright 2023 Gary J. Miller Orthopaedic Biomechanics Lab
 * SPDX-License-Identifier: AGPL-3.0
 */

/*Constants for resizing the spacings on the main screen*/

#ifndef SETTINGS_WINDOW_SIZE_CONSTANTS_H
#define SETTINGS_WINDOW_SIZE_CONSTANTS_H

/*Border Paddings between object A and object B*/
const int BUTTON_TO_BUTTON_PADDING_X = 35;
const int INSIDE_BUTTON_PADDING_X = 60;
const int INSIDE_RADIO_BUTTON_PADDING_X = 35;
const int APPLICATION_BORDER_TO_GROUP_BOX_PADDING_X = 55;
const int INSIDE_SPIN_BOX_PADDING_X = 25;
const int LABEL_TO_SPIN_BOX_PADDING_X = 15;
const int SPIN_BOX_TO_LABEL_PADDING_X = 25;
const int SMALL_GROUP_BOX_PADDING_X = 30;
const int GROUP_BOX_TO_SMALL_GROUP_BOX_X = 30;
const int GROUP_BOX_TO_GROUP_BOX_X = 30;
const int GROUP_BOX_TO_RADIO_BUTTON_X = 40;
const int BIG_GROUP_BOX_TO_SPIN_BOX_X = 115;

const int SMALL_GROUP_BOX_PADDING_Y = 30;
const int GROUP_BOX_TO_SMALL_GROUP_BOX_Y = 30;
const int CHECKBOX_TO_LABEL_Y = 30;
const int LABEL_TO_LABEL_PADDING_Y = 25;
const int GROUP_BOX_TO_GROUP_BOX_Y = 35;
const int SMALL_GROUP_BOX_TO_GROUP_BOX_Y = 30;
const int GROUP_BOX_TO_LABEL_PADDING_Y = 30;
const int GROUP_BOX_TO_RADIO_BUTTON_PADDING_Y = 30;
const int SPIN_BOX_TO_SPIN_BOX_PADDING_Y = 15;
const int INSIDE_BUTTON_PADDING_Y = 30;
const int INSIDE_RADIO_BUTTON_PADDING_Y = 10;
const int APPLICATION_BORDER_TO_GROUP_BOX_PADDING_Y = 30;
const int INSIDE_SPIN_BOX_PADDING_Y = 15;

#endif /* SETTINGS_WINDOW_SIZE_CONSTANTS_H */