[package]
name = "direct-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx.workspace = true
ordered-float = "5.5.0"
plotters = { version = "0.3.7", default-features = false, features = ["svg_backend",
"line_series", "point_series"] }

[build-dependencies]
cxx-build.workspace = true

[dev-dependencies]
proptest = "1.6"

[lints]
workspace = true

[lib]
crate-type=["staticlib", "cdylib"]
